/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// RegistryProviderVersionsResponseAttributesPermissions struct for RegistryProviderVersionsResponseAttributesPermissions
type RegistryProviderVersionsResponseAttributesPermissions struct {
	CanDelete      *bool `json:"can-delete,omitempty"`
	CanUploadAsset *bool `json:"can-upload-asset,omitempty"`
}

// NewRegistryProviderVersionsResponseAttributesPermissions instantiates a new RegistryProviderVersionsResponseAttributesPermissions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryProviderVersionsResponseAttributesPermissions() *RegistryProviderVersionsResponseAttributesPermissions {
	this := RegistryProviderVersionsResponseAttributesPermissions{}
	return &this
}

// NewRegistryProviderVersionsResponseAttributesPermissionsWithDefaults instantiates a new RegistryProviderVersionsResponseAttributesPermissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryProviderVersionsResponseAttributesPermissionsWithDefaults() *RegistryProviderVersionsResponseAttributesPermissions {
	this := RegistryProviderVersionsResponseAttributesPermissions{}
	return &this
}

// GetCanDelete returns the CanDelete field value if set, zero value otherwise.
func (o *RegistryProviderVersionsResponseAttributesPermissions) GetCanDelete() bool {
	if o == nil || o.CanDelete == nil {
		var ret bool
		return ret
	}
	return *o.CanDelete
}

// GetCanDeleteOk returns a tuple with the CanDelete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProviderVersionsResponseAttributesPermissions) GetCanDeleteOk() (*bool, bool) {
	if o == nil || o.CanDelete == nil {
		return nil, false
	}
	return o.CanDelete, true
}

// HasCanDelete returns a boolean if a field has been set.
func (o *RegistryProviderVersionsResponseAttributesPermissions) HasCanDelete() bool {
	if o != nil && o.CanDelete != nil {
		return true
	}

	return false
}

// SetCanDelete gets a reference to the given bool and assigns it to the CanDelete field.
func (o *RegistryProviderVersionsResponseAttributesPermissions) SetCanDelete(v bool) {
	o.CanDelete = &v
}

// GetCanUploadAsset returns the CanUploadAsset field value if set, zero value otherwise.
func (o *RegistryProviderVersionsResponseAttributesPermissions) GetCanUploadAsset() bool {
	if o == nil || o.CanUploadAsset == nil {
		var ret bool
		return ret
	}
	return *o.CanUploadAsset
}

// GetCanUploadAssetOk returns a tuple with the CanUploadAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProviderVersionsResponseAttributesPermissions) GetCanUploadAssetOk() (*bool, bool) {
	if o == nil || o.CanUploadAsset == nil {
		return nil, false
	}
	return o.CanUploadAsset, true
}

// HasCanUploadAsset returns a boolean if a field has been set.
func (o *RegistryProviderVersionsResponseAttributesPermissions) HasCanUploadAsset() bool {
	if o != nil && o.CanUploadAsset != nil {
		return true
	}

	return false
}

// SetCanUploadAsset gets a reference to the given bool and assigns it to the CanUploadAsset field.
func (o *RegistryProviderVersionsResponseAttributesPermissions) SetCanUploadAsset(v bool) {
	o.CanUploadAsset = &v
}

func (o RegistryProviderVersionsResponseAttributesPermissions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CanDelete != nil {
		toSerialize["can-delete"] = o.CanDelete
	}
	if o.CanUploadAsset != nil {
		toSerialize["can-upload-asset"] = o.CanUploadAsset
	}
	return json.Marshal(toSerialize)
}

type NullableRegistryProviderVersionsResponseAttributesPermissions struct {
	value *RegistryProviderVersionsResponseAttributesPermissions
	isSet bool
}

func (v NullableRegistryProviderVersionsResponseAttributesPermissions) Get() *RegistryProviderVersionsResponseAttributesPermissions {
	return v.value
}

func (v *NullableRegistryProviderVersionsResponseAttributesPermissions) Set(val *RegistryProviderVersionsResponseAttributesPermissions) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryProviderVersionsResponseAttributesPermissions) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryProviderVersionsResponseAttributesPermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryProviderVersionsResponseAttributesPermissions(val *RegistryProviderVersionsResponseAttributesPermissions) *NullableRegistryProviderVersionsResponseAttributesPermissions {
	return &NullableRegistryProviderVersionsResponseAttributesPermissions{value: val, isSet: true}
}

func (v NullableRegistryProviderVersionsResponseAttributesPermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryProviderVersionsResponseAttributesPermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
