/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// RegistryProviderVersionsResponse struct for RegistryProviderVersionsResponse
type RegistryProviderVersionsResponse struct {
	Data []RegistryProviderVersionsResponseData `json:"data,omitempty"`
}

// NewRegistryProviderVersionsResponse instantiates a new RegistryProviderVersionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryProviderVersionsResponse() *RegistryProviderVersionsResponse {
	this := RegistryProviderVersionsResponse{}
	return &this
}

// NewRegistryProviderVersionsResponseWithDefaults instantiates a new RegistryProviderVersionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryProviderVersionsResponseWithDefaults() *RegistryProviderVersionsResponse {
	this := RegistryProviderVersionsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RegistryProviderVersionsResponse) GetData() []RegistryProviderVersionsResponseData {
	if o == nil || o.Data == nil {
		var ret []RegistryProviderVersionsResponseData
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProviderVersionsResponse) GetDataOk() ([]RegistryProviderVersionsResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RegistryProviderVersionsResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []RegistryProviderVersionsResponseData and assigns it to the Data field.
func (o *RegistryProviderVersionsResponse) SetData(v []RegistryProviderVersionsResponseData) {
	o.Data = v
}

func (o RegistryProviderVersionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableRegistryProviderVersionsResponse struct {
	value *RegistryProviderVersionsResponse
	isSet bool
}

func (v NullableRegistryProviderVersionsResponse) Get() *RegistryProviderVersionsResponse {
	return v.value
}

func (v *NullableRegistryProviderVersionsResponse) Set(val *RegistryProviderVersionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryProviderVersionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryProviderVersionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryProviderVersionsResponse(val *RegistryProviderVersionsResponse) *NullableRegistryProviderVersionsResponse {
	return &NullableRegistryProviderVersionsResponse{value: val, isSet: true}
}

func (v NullableRegistryProviderVersionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryProviderVersionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
