/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// CreateRegistryProviderVersionData struct for CreateRegistryProviderVersionData
type CreateRegistryProviderVersionData struct {
	Type       string                                      `json:"type"`
	Attributes CreateRegistryProviderVersionDataAttributes `json:"attributes"`
}

// NewCreateRegistryProviderVersionData instantiates a new CreateRegistryProviderVersionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRegistryProviderVersionData(type_ string, attributes CreateRegistryProviderVersionDataAttributes) *CreateRegistryProviderVersionData {
	this := CreateRegistryProviderVersionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateRegistryProviderVersionDataWithDefaults instantiates a new CreateRegistryProviderVersionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRegistryProviderVersionDataWithDefaults() *CreateRegistryProviderVersionData {
	this := CreateRegistryProviderVersionData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateRegistryProviderVersionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderVersionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateRegistryProviderVersionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateRegistryProviderVersionData) GetAttributes() CreateRegistryProviderVersionDataAttributes {
	if o == nil {
		var ret CreateRegistryProviderVersionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderVersionData) GetAttributesOk() (*CreateRegistryProviderVersionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateRegistryProviderVersionData) SetAttributes(v CreateRegistryProviderVersionDataAttributes) {
	o.Attributes = v
}

func (o CreateRegistryProviderVersionData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableCreateRegistryProviderVersionData struct {
	value *CreateRegistryProviderVersionData
	isSet bool
}

func (v NullableCreateRegistryProviderVersionData) Get() *CreateRegistryProviderVersionData {
	return v.value
}

func (v *NullableCreateRegistryProviderVersionData) Set(val *CreateRegistryProviderVersionData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRegistryProviderVersionData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRegistryProviderVersionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRegistryProviderVersionData(val *CreateRegistryProviderVersionData) *NullableCreateRegistryProviderVersionData {
	return &NullableCreateRegistryProviderVersionData{value: val, isSet: true}
}

func (v NullableCreateRegistryProviderVersionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRegistryProviderVersionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
