/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// CreateRegistryProviderResponseData struct for CreateRegistryProviderResponseData
type CreateRegistryProviderResponseData struct {
	Id         *string                                       `json:"id,omitempty"`
	Type       *string                                       `json:"type,omitempty"`
	Attributes *CreateRegistryProviderResponseDataAttributes `json:"attributes,omitempty"`
}

// NewCreateRegistryProviderResponseData instantiates a new CreateRegistryProviderResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRegistryProviderResponseData() *CreateRegistryProviderResponseData {
	this := CreateRegistryProviderResponseData{}
	return &this
}

// NewCreateRegistryProviderResponseDataWithDefaults instantiates a new CreateRegistryProviderResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRegistryProviderResponseDataWithDefaults() *CreateRegistryProviderResponseData {
	this := CreateRegistryProviderResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateRegistryProviderResponseData) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderResponseData) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateRegistryProviderResponseData) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateRegistryProviderResponseData) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateRegistryProviderResponseData) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderResponseData) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateRegistryProviderResponseData) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateRegistryProviderResponseData) SetType(v string) {
	o.Type = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *CreateRegistryProviderResponseData) GetAttributes() CreateRegistryProviderResponseDataAttributes {
	if o == nil || o.Attributes == nil {
		var ret CreateRegistryProviderResponseDataAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderResponseData) GetAttributesOk() (*CreateRegistryProviderResponseDataAttributes, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *CreateRegistryProviderResponseData) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given CreateRegistryProviderResponseDataAttributes and assigns it to the Attributes field.
func (o *CreateRegistryProviderResponseData) SetAttributes(v CreateRegistryProviderResponseDataAttributes) {
	o.Attributes = &v
}

func (o CreateRegistryProviderResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableCreateRegistryProviderResponseData struct {
	value *CreateRegistryProviderResponseData
	isSet bool
}

func (v NullableCreateRegistryProviderResponseData) Get() *CreateRegistryProviderResponseData {
	return v.value
}

func (v *NullableCreateRegistryProviderResponseData) Set(val *CreateRegistryProviderResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRegistryProviderResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRegistryProviderResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRegistryProviderResponseData(val *CreateRegistryProviderResponseData) *NullableCreateRegistryProviderResponseData {
	return &NullableCreateRegistryProviderResponseData{value: val, isSet: true}
}

func (v NullableCreateRegistryProviderResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRegistryProviderResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
