/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// GpgKeyResponseData struct for GpgKeyResponseData
type GpgKeyResponseData struct {
	Attributes *GpgKeyResponseDataAttributes `json:"attributes,omitempty"`
}

// NewGpgKeyResponseData instantiates a new GpgKeyResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGpgKeyResponseData() *GpgKeyResponseData {
	this := GpgKeyResponseData{}
	return &this
}

// NewGpgKeyResponseDataWithDefaults instantiates a new GpgKeyResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGpgKeyResponseDataWithDefaults() *GpgKeyResponseData {
	this := GpgKeyResponseData{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *GpgKeyResponseData) GetAttributes() GpgKeyResponseDataAttributes {
	if o == nil || o.Attributes == nil {
		var ret GpgKeyResponseDataAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyResponseData) GetAttributesOk() (*GpgKeyResponseDataAttributes, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *GpgKeyResponseData) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given GpgKeyResponseDataAttributes and assigns it to the Attributes field.
func (o *GpgKeyResponseData) SetAttributes(v GpgKeyResponseDataAttributes) {
	o.Attributes = &v
}

func (o GpgKeyResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableGpgKeyResponseData struct {
	value *GpgKeyResponseData
	isSet bool
}

func (v NullableGpgKeyResponseData) Get() *GpgKeyResponseData {
	return v.value
}

func (v *NullableGpgKeyResponseData) Set(val *GpgKeyResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGpgKeyResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGpgKeyResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGpgKeyResponseData(val *GpgKeyResponseData) *NullableGpgKeyResponseData {
	return &NullableGpgKeyResponseData{value: val, isSet: true}
}

func (v NullableGpgKeyResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGpgKeyResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
