/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// Permissions struct for Permissions
type Permissions struct {
	CanDelete      *bool `json:"can-delete,omitempty"`
	CanUploadAsset *bool `json:"can-upload-asset,omitempty"`
}

// NewPermissions instantiates a new Permissions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissions() *Permissions {
	this := Permissions{}
	return &this
}

// NewPermissionsWithDefaults instantiates a new Permissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionsWithDefaults() *Permissions {
	this := Permissions{}
	return &this
}

// GetCanDelete returns the CanDelete field value if set, zero value otherwise.
func (o *Permissions) GetCanDelete() bool {
	if o == nil || o.CanDelete == nil {
		var ret bool
		return ret
	}
	return *o.CanDelete
}

// GetCanDeleteOk returns a tuple with the CanDelete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Permissions) GetCanDeleteOk() (*bool, bool) {
	if o == nil || o.CanDelete == nil {
		return nil, false
	}
	return o.CanDelete, true
}

// HasCanDelete returns a boolean if a field has been set.
func (o *Permissions) HasCanDelete() bool {
	if o != nil && o.CanDelete != nil {
		return true
	}

	return false
}

// SetCanDelete gets a reference to the given bool and assigns it to the CanDelete field.
func (o *Permissions) SetCanDelete(v bool) {
	o.CanDelete = &v
}

// GetCanUploadAsset returns the CanUploadAsset field value if set, zero value otherwise.
func (o *Permissions) GetCanUploadAsset() bool {
	if o == nil || o.CanUploadAsset == nil {
		var ret bool
		return ret
	}
	return *o.CanUploadAsset
}

// GetCanUploadAssetOk returns a tuple with the CanUploadAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Permissions) GetCanUploadAssetOk() (*bool, bool) {
	if o == nil || o.CanUploadAsset == nil {
		return nil, false
	}
	return o.CanUploadAsset, true
}

// HasCanUploadAsset returns a boolean if a field has been set.
func (o *Permissions) HasCanUploadAsset() bool {
	if o != nil && o.CanUploadAsset != nil {
		return true
	}

	return false
}

// SetCanUploadAsset gets a reference to the given bool and assigns it to the CanUploadAsset field.
func (o *Permissions) SetCanUploadAsset(v bool) {
	o.CanUploadAsset = &v
}

func (o Permissions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CanDelete != nil {
		toSerialize["can-delete"] = o.CanDelete
	}
	if o.CanUploadAsset != nil {
		toSerialize["can-upload-asset"] = o.CanUploadAsset
	}
	return json.Marshal(toSerialize)
}

type NullablePermissions struct {
	value *Permissions
	isSet bool
}

func (v NullablePermissions) Get() *Permissions {
	return v.value
}

func (v *NullablePermissions) Set(val *Permissions) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissions) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissions(val *Permissions) *NullablePermissions {
	return &NullablePermissions{value: val, isSet: true}
}

func (v NullablePermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
