/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// CreateProviderPlatformDataAttributes struct for CreateProviderPlatformDataAttributes
type CreateProviderPlatformDataAttributes struct {
	Os       string `json:"os"`
	Arch     string `json:"arch"`
	Filename string `json:"filename"`
	Shasum   string `json:"shasum"`
}

// NewCreateProviderPlatformDataAttributes instantiates a new CreateProviderPlatformDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProviderPlatformDataAttributes(os string, arch string, filename string, shasum string) *CreateProviderPlatformDataAttributes {
	this := CreateProviderPlatformDataAttributes{}
	this.Os = os
	this.Arch = arch
	this.Filename = filename
	this.Shasum = shasum
	return &this
}

// NewCreateProviderPlatformDataAttributesWithDefaults instantiates a new CreateProviderPlatformDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProviderPlatformDataAttributesWithDefaults() *CreateProviderPlatformDataAttributes {
	this := CreateProviderPlatformDataAttributes{}
	return &this
}

// GetOs returns the Os field value
func (o *CreateProviderPlatformDataAttributes) GetOs() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Os
}

// GetOsOk returns a tuple with the Os field value
// and a boolean to check if the value has been set.
func (o *CreateProviderPlatformDataAttributes) GetOsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Os, true
}

// SetOs sets field value
func (o *CreateProviderPlatformDataAttributes) SetOs(v string) {
	o.Os = v
}

// GetArch returns the Arch field value
func (o *CreateProviderPlatformDataAttributes) GetArch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Arch
}

// GetArchOk returns a tuple with the Arch field value
// and a boolean to check if the value has been set.
func (o *CreateProviderPlatformDataAttributes) GetArchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Arch, true
}

// SetArch sets field value
func (o *CreateProviderPlatformDataAttributes) SetArch(v string) {
	o.Arch = v
}

// GetFilename returns the Filename field value
func (o *CreateProviderPlatformDataAttributes) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *CreateProviderPlatformDataAttributes) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *CreateProviderPlatformDataAttributes) SetFilename(v string) {
	o.Filename = v
}

// GetShasum returns the Shasum field value
func (o *CreateProviderPlatformDataAttributes) GetShasum() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Shasum
}

// GetShasumOk returns a tuple with the Shasum field value
// and a boolean to check if the value has been set.
func (o *CreateProviderPlatformDataAttributes) GetShasumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Shasum, true
}

// SetShasum sets field value
func (o *CreateProviderPlatformDataAttributes) SetShasum(v string) {
	o.Shasum = v
}

func (o CreateProviderPlatformDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["os"] = o.Os
	}
	if true {
		toSerialize["arch"] = o.Arch
	}
	if true {
		toSerialize["filename"] = o.Filename
	}
	if true {
		toSerialize["shasum"] = o.Shasum
	}
	return json.Marshal(toSerialize)
}

type NullableCreateProviderPlatformDataAttributes struct {
	value *CreateProviderPlatformDataAttributes
	isSet bool
}

func (v NullableCreateProviderPlatformDataAttributes) Get() *CreateProviderPlatformDataAttributes {
	return v.value
}

func (v *NullableCreateProviderPlatformDataAttributes) Set(val *CreateProviderPlatformDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProviderPlatformDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProviderPlatformDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProviderPlatformDataAttributes(val *CreateProviderPlatformDataAttributes) *NullableCreateProviderPlatformDataAttributes {
	return &NullableCreateProviderPlatformDataAttributes{value: val, isSet: true}
}

func (v NullableCreateProviderPlatformDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProviderPlatformDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
