/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// GpgKeyResponseDataAttributes struct for GpgKeyResponseDataAttributes
type GpgKeyResponseDataAttributes struct {
	Namespace  *string `json:"namespace,omitempty"`
	AsciiArmor *string `json:"ascii-armor,omitempty"`
	KeyId      *string `json:"key-id,omitempty"`
	CreatedAt  *string `json:"created-at,omitempty"`
	UpdatedAt  *string `json:"updated-at,omitempty"`
}

// NewGpgKeyResponseDataAttributes instantiates a new GpgKeyResponseDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGpgKeyResponseDataAttributes() *GpgKeyResponseDataAttributes {
	this := GpgKeyResponseDataAttributes{}
	return &this
}

// NewGpgKeyResponseDataAttributesWithDefaults instantiates a new GpgKeyResponseDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGpgKeyResponseDataAttributesWithDefaults() *GpgKeyResponseDataAttributes {
	this := GpgKeyResponseDataAttributes{}
	return &this
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *GpgKeyResponseDataAttributes) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyResponseDataAttributes) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *GpgKeyResponseDataAttributes) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *GpgKeyResponseDataAttributes) SetNamespace(v string) {
	o.Namespace = &v
}

// GetAsciiArmor returns the AsciiArmor field value if set, zero value otherwise.
func (o *GpgKeyResponseDataAttributes) GetAsciiArmor() string {
	if o == nil || o.AsciiArmor == nil {
		var ret string
		return ret
	}
	return *o.AsciiArmor
}

// GetAsciiArmorOk returns a tuple with the AsciiArmor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyResponseDataAttributes) GetAsciiArmorOk() (*string, bool) {
	if o == nil || o.AsciiArmor == nil {
		return nil, false
	}
	return o.AsciiArmor, true
}

// HasAsciiArmor returns a boolean if a field has been set.
func (o *GpgKeyResponseDataAttributes) HasAsciiArmor() bool {
	if o != nil && o.AsciiArmor != nil {
		return true
	}

	return false
}

// SetAsciiArmor gets a reference to the given string and assigns it to the AsciiArmor field.
func (o *GpgKeyResponseDataAttributes) SetAsciiArmor(v string) {
	o.AsciiArmor = &v
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *GpgKeyResponseDataAttributes) GetKeyId() string {
	if o == nil || o.KeyId == nil {
		var ret string
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyResponseDataAttributes) GetKeyIdOk() (*string, bool) {
	if o == nil || o.KeyId == nil {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *GpgKeyResponseDataAttributes) HasKeyId() bool {
	if o != nil && o.KeyId != nil {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given string and assigns it to the KeyId field.
func (o *GpgKeyResponseDataAttributes) SetKeyId(v string) {
	o.KeyId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GpgKeyResponseDataAttributes) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyResponseDataAttributes) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GpgKeyResponseDataAttributes) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GpgKeyResponseDataAttributes) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GpgKeyResponseDataAttributes) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyResponseDataAttributes) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GpgKeyResponseDataAttributes) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GpgKeyResponseDataAttributes) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o GpgKeyResponseDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Namespace != nil {
		toSerialize["namespace"] = o.Namespace
	}
	if o.AsciiArmor != nil {
		toSerialize["ascii-armor"] = o.AsciiArmor
	}
	if o.KeyId != nil {
		toSerialize["key-id"] = o.KeyId
	}
	if o.CreatedAt != nil {
		toSerialize["created-at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated-at"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableGpgKeyResponseDataAttributes struct {
	value *GpgKeyResponseDataAttributes
	isSet bool
}

func (v NullableGpgKeyResponseDataAttributes) Get() *GpgKeyResponseDataAttributes {
	return v.value
}

func (v *NullableGpgKeyResponseDataAttributes) Set(val *GpgKeyResponseDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableGpgKeyResponseDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableGpgKeyResponseDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGpgKeyResponseDataAttributes(val *GpgKeyResponseDataAttributes) *NullableGpgKeyResponseDataAttributes {
	return &NullableGpgKeyResponseDataAttributes{value: val, isSet: true}
}

func (v NullableGpgKeyResponseDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGpgKeyResponseDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
