/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// RegistryProvidersResponseAttributes struct for RegistryProvidersResponseAttributes
type RegistryProvidersResponseAttributes struct {
	Name        *string      `json:"name,omitempty"`
	Namespace   *string      `json:"namespace,omitempty"`
	CreatedAt   *string      `json:"created-at,omitempty"`
	UpdatedAt   *string      `json:"updated-at,omitempty"`
	Protocols   []string     `json:"protocols,omitempty"`
	Permissions *Permissions `json:"permissions,omitempty"`
}

// NewRegistryProvidersResponseAttributes instantiates a new RegistryProvidersResponseAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryProvidersResponseAttributes() *RegistryProvidersResponseAttributes {
	this := RegistryProvidersResponseAttributes{}
	return &this
}

// NewRegistryProvidersResponseAttributesWithDefaults instantiates a new RegistryProvidersResponseAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryProvidersResponseAttributesWithDefaults() *RegistryProvidersResponseAttributes {
	this := RegistryProvidersResponseAttributes{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RegistryProvidersResponseAttributes) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProvidersResponseAttributes) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RegistryProvidersResponseAttributes) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RegistryProvidersResponseAttributes) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *RegistryProvidersResponseAttributes) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProvidersResponseAttributes) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *RegistryProvidersResponseAttributes) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *RegistryProvidersResponseAttributes) SetNamespace(v string) {
	o.Namespace = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *RegistryProvidersResponseAttributes) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProvidersResponseAttributes) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *RegistryProvidersResponseAttributes) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *RegistryProvidersResponseAttributes) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *RegistryProvidersResponseAttributes) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProvidersResponseAttributes) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *RegistryProvidersResponseAttributes) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *RegistryProvidersResponseAttributes) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetProtocols returns the Protocols field value if set, zero value otherwise.
func (o *RegistryProvidersResponseAttributes) GetProtocols() []string {
	if o == nil || o.Protocols == nil {
		var ret []string
		return ret
	}
	return o.Protocols
}

// GetProtocolsOk returns a tuple with the Protocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProvidersResponseAttributes) GetProtocolsOk() ([]string, bool) {
	if o == nil || o.Protocols == nil {
		return nil, false
	}
	return o.Protocols, true
}

// HasProtocols returns a boolean if a field has been set.
func (o *RegistryProvidersResponseAttributes) HasProtocols() bool {
	if o != nil && o.Protocols != nil {
		return true
	}

	return false
}

// SetProtocols gets a reference to the given []string and assigns it to the Protocols field.
func (o *RegistryProvidersResponseAttributes) SetProtocols(v []string) {
	o.Protocols = v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *RegistryProvidersResponseAttributes) GetPermissions() Permissions {
	if o == nil || o.Permissions == nil {
		var ret Permissions
		return ret
	}
	return *o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProvidersResponseAttributes) GetPermissionsOk() (*Permissions, bool) {
	if o == nil || o.Permissions == nil {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *RegistryProvidersResponseAttributes) HasPermissions() bool {
	if o != nil && o.Permissions != nil {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given Permissions and assigns it to the Permissions field.
func (o *RegistryProvidersResponseAttributes) SetPermissions(v Permissions) {
	o.Permissions = &v
}

func (o RegistryProvidersResponseAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Namespace != nil {
		toSerialize["namespace"] = o.Namespace
	}
	if o.CreatedAt != nil {
		toSerialize["created-at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated-at"] = o.UpdatedAt
	}
	if o.Protocols != nil {
		toSerialize["protocols"] = o.Protocols
	}
	if o.Permissions != nil {
		toSerialize["permissions"] = o.Permissions
	}
	return json.Marshal(toSerialize)
}

type NullableRegistryProvidersResponseAttributes struct {
	value *RegistryProvidersResponseAttributes
	isSet bool
}

func (v NullableRegistryProvidersResponseAttributes) Get() *RegistryProvidersResponseAttributes {
	return v.value
}

func (v *NullableRegistryProvidersResponseAttributes) Set(val *RegistryProvidersResponseAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryProvidersResponseAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryProvidersResponseAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryProvidersResponseAttributes(val *RegistryProvidersResponseAttributes) *NullableRegistryProvidersResponseAttributes {
	return &NullableRegistryProvidersResponseAttributes{value: val, isSet: true}
}

func (v NullableRegistryProvidersResponseAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryProvidersResponseAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
