/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// ProviderPlatformResponseData struct for ProviderPlatformResponseData
type ProviderPlatformResponseData struct {
	Id         *string                                 `json:"id,omitempty"`
	Type       *string                                 `json:"type,omitempty"`
	Attributes *ProviderPlatformResponseDataAttributes `json:"attributes,omitempty"`
	Links      *ProviderPlatformResponseDataLinks      `json:"links,omitempty"`
}

// NewProviderPlatformResponseData instantiates a new ProviderPlatformResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderPlatformResponseData() *ProviderPlatformResponseData {
	this := ProviderPlatformResponseData{}
	return &this
}

// NewProviderPlatformResponseDataWithDefaults instantiates a new ProviderPlatformResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderPlatformResponseDataWithDefaults() *ProviderPlatformResponseData {
	this := ProviderPlatformResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProviderPlatformResponseData) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPlatformResponseData) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProviderPlatformResponseData) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProviderPlatformResponseData) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ProviderPlatformResponseData) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPlatformResponseData) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ProviderPlatformResponseData) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ProviderPlatformResponseData) SetType(v string) {
	o.Type = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ProviderPlatformResponseData) GetAttributes() ProviderPlatformResponseDataAttributes {
	if o == nil || o.Attributes == nil {
		var ret ProviderPlatformResponseDataAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPlatformResponseData) GetAttributesOk() (*ProviderPlatformResponseDataAttributes, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ProviderPlatformResponseData) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given ProviderPlatformResponseDataAttributes and assigns it to the Attributes field.
func (o *ProviderPlatformResponseData) SetAttributes(v ProviderPlatformResponseDataAttributes) {
	o.Attributes = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ProviderPlatformResponseData) GetLinks() ProviderPlatformResponseDataLinks {
	if o == nil || o.Links == nil {
		var ret ProviderPlatformResponseDataLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPlatformResponseData) GetLinksOk() (*ProviderPlatformResponseDataLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ProviderPlatformResponseData) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given ProviderPlatformResponseDataLinks and assigns it to the Links field.
func (o *ProviderPlatformResponseData) SetLinks(v ProviderPlatformResponseDataLinks) {
	o.Links = &v
}

func (o ProviderPlatformResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableProviderPlatformResponseData struct {
	value *ProviderPlatformResponseData
	isSet bool
}

func (v NullableProviderPlatformResponseData) Get() *ProviderPlatformResponseData {
	return v.value
}

func (v *NullableProviderPlatformResponseData) Set(val *ProviderPlatformResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderPlatformResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderPlatformResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderPlatformResponseData(val *ProviderPlatformResponseData) *NullableProviderPlatformResponseData {
	return &NullableProviderPlatformResponseData{value: val, isSet: true}
}

func (v NullableProviderPlatformResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderPlatformResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
