/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// RegistryProvidersResponseData struct for RegistryProvidersResponseData
type RegistryProvidersResponseData struct {
	Id         *string                              `json:"id,omitempty"`
	Type       *string                              `json:"type,omitempty"`
	Attributes *RegistryProvidersResponseAttributes `json:"attributes,omitempty"`
}

// NewRegistryProvidersResponseData instantiates a new RegistryProvidersResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryProvidersResponseData() *RegistryProvidersResponseData {
	this := RegistryProvidersResponseData{}
	return &this
}

// NewRegistryProvidersResponseDataWithDefaults instantiates a new RegistryProvidersResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryProvidersResponseDataWithDefaults() *RegistryProvidersResponseData {
	this := RegistryProvidersResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RegistryProvidersResponseData) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProvidersResponseData) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RegistryProvidersResponseData) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RegistryProvidersResponseData) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RegistryProvidersResponseData) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProvidersResponseData) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RegistryProvidersResponseData) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RegistryProvidersResponseData) SetType(v string) {
	o.Type = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *RegistryProvidersResponseData) GetAttributes() RegistryProvidersResponseAttributes {
	if o == nil || o.Attributes == nil {
		var ret RegistryProvidersResponseAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryProvidersResponseData) GetAttributesOk() (*RegistryProvidersResponseAttributes, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *RegistryProvidersResponseData) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given RegistryProvidersResponseAttributes and assigns it to the Attributes field.
func (o *RegistryProvidersResponseData) SetAttributes(v RegistryProvidersResponseAttributes) {
	o.Attributes = &v
}

func (o RegistryProvidersResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableRegistryProvidersResponseData struct {
	value *RegistryProvidersResponseData
	isSet bool
}

func (v NullableRegistryProvidersResponseData) Get() *RegistryProvidersResponseData {
	return v.value
}

func (v *NullableRegistryProvidersResponseData) Set(val *RegistryProvidersResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryProvidersResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryProvidersResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryProvidersResponseData(val *RegistryProvidersResponseData) *NullableRegistryProvidersResponseData {
	return &NullableRegistryProvidersResponseData{value: val, isSet: true}
}

func (v NullableRegistryProvidersResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryProvidersResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
