/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// CreateProviderPlatformData struct for CreateProviderPlatformData
type CreateProviderPlatformData struct {
	Type       string                               `json:"type"`
	Attributes CreateProviderPlatformDataAttributes `json:"attributes"`
}

// NewCreateProviderPlatformData instantiates a new CreateProviderPlatformData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProviderPlatformData(type_ string, attributes CreateProviderPlatformDataAttributes) *CreateProviderPlatformData {
	this := CreateProviderPlatformData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateProviderPlatformDataWithDefaults instantiates a new CreateProviderPlatformData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProviderPlatformDataWithDefaults() *CreateProviderPlatformData {
	this := CreateProviderPlatformData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateProviderPlatformData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateProviderPlatformData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateProviderPlatformData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateProviderPlatformData) GetAttributes() CreateProviderPlatformDataAttributes {
	if o == nil {
		var ret CreateProviderPlatformDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateProviderPlatformData) GetAttributesOk() (*CreateProviderPlatformDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateProviderPlatformData) SetAttributes(v CreateProviderPlatformDataAttributes) {
	o.Attributes = v
}

func (o CreateProviderPlatformData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableCreateProviderPlatformData struct {
	value *CreateProviderPlatformData
	isSet bool
}

func (v NullableCreateProviderPlatformData) Get() *CreateProviderPlatformData {
	return v.value
}

func (v *NullableCreateProviderPlatformData) Set(val *CreateProviderPlatformData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProviderPlatformData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProviderPlatformData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProviderPlatformData(val *CreateProviderPlatformData) *NullableCreateProviderPlatformData {
	return &NullableCreateProviderPlatformData{value: val, isSet: true}
}

func (v NullableCreateProviderPlatformData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProviderPlatformData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
