/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// CreateRegistryProviderVersionResponseData struct for CreateRegistryProviderVersionResponseData
type CreateRegistryProviderVersionResponseData struct {
	Id         *string                                         `json:"id,omitempty"`
	Type       *string                                         `json:"type,omitempty"`
	Attributes *RegistryProviderVersionsResponseAttributes     `json:"attributes,omitempty"`
	Links      *CreateRegistryProviderVersionResponseDataLinks `json:"links,omitempty"`
}

// NewCreateRegistryProviderVersionResponseData instantiates a new CreateRegistryProviderVersionResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRegistryProviderVersionResponseData() *CreateRegistryProviderVersionResponseData {
	this := CreateRegistryProviderVersionResponseData{}
	return &this
}

// NewCreateRegistryProviderVersionResponseDataWithDefaults instantiates a new CreateRegistryProviderVersionResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRegistryProviderVersionResponseDataWithDefaults() *CreateRegistryProviderVersionResponseData {
	this := CreateRegistryProviderVersionResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateRegistryProviderVersionResponseData) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderVersionResponseData) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateRegistryProviderVersionResponseData) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateRegistryProviderVersionResponseData) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateRegistryProviderVersionResponseData) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderVersionResponseData) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateRegistryProviderVersionResponseData) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateRegistryProviderVersionResponseData) SetType(v string) {
	o.Type = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *CreateRegistryProviderVersionResponseData) GetAttributes() RegistryProviderVersionsResponseAttributes {
	if o == nil || o.Attributes == nil {
		var ret RegistryProviderVersionsResponseAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderVersionResponseData) GetAttributesOk() (*RegistryProviderVersionsResponseAttributes, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *CreateRegistryProviderVersionResponseData) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given RegistryProviderVersionsResponseAttributes and assigns it to the Attributes field.
func (o *CreateRegistryProviderVersionResponseData) SetAttributes(v RegistryProviderVersionsResponseAttributes) {
	o.Attributes = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CreateRegistryProviderVersionResponseData) GetLinks() CreateRegistryProviderVersionResponseDataLinks {
	if o == nil || o.Links == nil {
		var ret CreateRegistryProviderVersionResponseDataLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderVersionResponseData) GetLinksOk() (*CreateRegistryProviderVersionResponseDataLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CreateRegistryProviderVersionResponseData) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given CreateRegistryProviderVersionResponseDataLinks and assigns it to the Links field.
func (o *CreateRegistryProviderVersionResponseData) SetLinks(v CreateRegistryProviderVersionResponseDataLinks) {
	o.Links = &v
}

func (o CreateRegistryProviderVersionResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableCreateRegistryProviderVersionResponseData struct {
	value *CreateRegistryProviderVersionResponseData
	isSet bool
}

func (v NullableCreateRegistryProviderVersionResponseData) Get() *CreateRegistryProviderVersionResponseData {
	return v.value
}

func (v *NullableCreateRegistryProviderVersionResponseData) Set(val *CreateRegistryProviderVersionResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRegistryProviderVersionResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRegistryProviderVersionResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRegistryProviderVersionResponseData(val *CreateRegistryProviderVersionResponseData) *NullableCreateRegistryProviderVersionResponseData {
	return &NullableCreateRegistryProviderVersionResponseData{value: val, isSet: true}
}

func (v NullableCreateRegistryProviderVersionResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRegistryProviderVersionResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
