/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// CreateRegistryProviderVersionResponseLinks struct for CreateRegistryProviderVersionResponseLinks
type CreateRegistryProviderVersionResponseLinks struct {
	ShasumsUpload    *string `json:"shasums-upload,omitempty"`
	ShasumsSigUpload *string `json:"shasums-sig-upload,omitempty"`
}

// NewCreateRegistryProviderVersionResponseLinks instantiates a new CreateRegistryProviderVersionResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRegistryProviderVersionResponseLinks() *CreateRegistryProviderVersionResponseLinks {
	this := CreateRegistryProviderVersionResponseLinks{}
	return &this
}

// NewCreateRegistryProviderVersionResponseLinksWithDefaults instantiates a new CreateRegistryProviderVersionResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRegistryProviderVersionResponseLinksWithDefaults() *CreateRegistryProviderVersionResponseLinks {
	this := CreateRegistryProviderVersionResponseLinks{}
	return &this
}

// GetShasumsUpload returns the ShasumsUpload field value if set, zero value otherwise.
func (o *CreateRegistryProviderVersionResponseLinks) GetShasumsUpload() string {
	if o == nil || o.ShasumsUpload == nil {
		var ret string
		return ret
	}
	return *o.ShasumsUpload
}

// GetShasumsUploadOk returns a tuple with the ShasumsUpload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderVersionResponseLinks) GetShasumsUploadOk() (*string, bool) {
	if o == nil || o.ShasumsUpload == nil {
		return nil, false
	}
	return o.ShasumsUpload, true
}

// HasShasumsUpload returns a boolean if a field has been set.
func (o *CreateRegistryProviderVersionResponseLinks) HasShasumsUpload() bool {
	if o != nil && o.ShasumsUpload != nil {
		return true
	}

	return false
}

// SetShasumsUpload gets a reference to the given string and assigns it to the ShasumsUpload field.
func (o *CreateRegistryProviderVersionResponseLinks) SetShasumsUpload(v string) {
	o.ShasumsUpload = &v
}

// GetShasumsSigUpload returns the ShasumsSigUpload field value if set, zero value otherwise.
func (o *CreateRegistryProviderVersionResponseLinks) GetShasumsSigUpload() string {
	if o == nil || o.ShasumsSigUpload == nil {
		var ret string
		return ret
	}
	return *o.ShasumsSigUpload
}

// GetShasumsSigUploadOk returns a tuple with the ShasumsSigUpload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderVersionResponseLinks) GetShasumsSigUploadOk() (*string, bool) {
	if o == nil || o.ShasumsSigUpload == nil {
		return nil, false
	}
	return o.ShasumsSigUpload, true
}

// HasShasumsSigUpload returns a boolean if a field has been set.
func (o *CreateRegistryProviderVersionResponseLinks) HasShasumsSigUpload() bool {
	if o != nil && o.ShasumsSigUpload != nil {
		return true
	}

	return false
}

// SetShasumsSigUpload gets a reference to the given string and assigns it to the ShasumsSigUpload field.
func (o *CreateRegistryProviderVersionResponseLinks) SetShasumsSigUpload(v string) {
	o.ShasumsSigUpload = &v
}

func (o CreateRegistryProviderVersionResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ShasumsUpload != nil {
		toSerialize["shasums-upload"] = o.ShasumsUpload
	}
	if o.ShasumsSigUpload != nil {
		toSerialize["shasums-sig-upload"] = o.ShasumsSigUpload
	}
	return json.Marshal(toSerialize)
}

type NullableCreateRegistryProviderVersionResponseLinks struct {
	value *CreateRegistryProviderVersionResponseLinks
	isSet bool
}

func (v NullableCreateRegistryProviderVersionResponseLinks) Get() *CreateRegistryProviderVersionResponseLinks {
	return v.value
}

func (v *NullableCreateRegistryProviderVersionResponseLinks) Set(val *CreateRegistryProviderVersionResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRegistryProviderVersionResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRegistryProviderVersionResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRegistryProviderVersionResponseLinks(val *CreateRegistryProviderVersionResponseLinks) *NullableCreateRegistryProviderVersionResponseLinks {
	return &NullableCreateRegistryProviderVersionResponseLinks{value: val, isSet: true}
}

func (v NullableCreateRegistryProviderVersionResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRegistryProviderVersionResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
