/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// ProviderPlatformResponseDataLinks struct for ProviderPlatformResponseDataLinks
type ProviderPlatformResponseDataLinks struct {
	ProviderBinaryUpload   *string `json:"provider-binary-upload,omitempty"`
	ProviderBinaryDownload *string `json:"provider-binary-download,omitempty"`
}

// NewProviderPlatformResponseDataLinks instantiates a new ProviderPlatformResponseDataLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderPlatformResponseDataLinks() *ProviderPlatformResponseDataLinks {
	this := ProviderPlatformResponseDataLinks{}
	return &this
}

// NewProviderPlatformResponseDataLinksWithDefaults instantiates a new ProviderPlatformResponseDataLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderPlatformResponseDataLinksWithDefaults() *ProviderPlatformResponseDataLinks {
	this := ProviderPlatformResponseDataLinks{}
	return &this
}

// GetProviderBinaryUpload returns the ProviderBinaryUpload field value if set, zero value otherwise.
func (o *ProviderPlatformResponseDataLinks) GetProviderBinaryUpload() string {
	if o == nil || o.ProviderBinaryUpload == nil {
		var ret string
		return ret
	}
	return *o.ProviderBinaryUpload
}

// GetProviderBinaryUploadOk returns a tuple with the ProviderBinaryUpload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPlatformResponseDataLinks) GetProviderBinaryUploadOk() (*string, bool) {
	if o == nil || o.ProviderBinaryUpload == nil {
		return nil, false
	}
	return o.ProviderBinaryUpload, true
}

// HasProviderBinaryUpload returns a boolean if a field has been set.
func (o *ProviderPlatformResponseDataLinks) HasProviderBinaryUpload() bool {
	if o != nil && o.ProviderBinaryUpload != nil {
		return true
	}

	return false
}

// SetProviderBinaryUpload gets a reference to the given string and assigns it to the ProviderBinaryUpload field.
func (o *ProviderPlatformResponseDataLinks) SetProviderBinaryUpload(v string) {
	o.ProviderBinaryUpload = &v
}

// GetProviderBinaryDownload returns the ProviderBinaryDownload field value if set, zero value otherwise.
func (o *ProviderPlatformResponseDataLinks) GetProviderBinaryDownload() string {
	if o == nil || o.ProviderBinaryDownload == nil {
		var ret string
		return ret
	}
	return *o.ProviderBinaryDownload
}

// GetProviderBinaryDownloadOk returns a tuple with the ProviderBinaryDownload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderPlatformResponseDataLinks) GetProviderBinaryDownloadOk() (*string, bool) {
	if o == nil || o.ProviderBinaryDownload == nil {
		return nil, false
	}
	return o.ProviderBinaryDownload, true
}

// HasProviderBinaryDownload returns a boolean if a field has been set.
func (o *ProviderPlatformResponseDataLinks) HasProviderBinaryDownload() bool {
	if o != nil && o.ProviderBinaryDownload != nil {
		return true
	}

	return false
}

// SetProviderBinaryDownload gets a reference to the given string and assigns it to the ProviderBinaryDownload field.
func (o *ProviderPlatformResponseDataLinks) SetProviderBinaryDownload(v string) {
	o.ProviderBinaryDownload = &v
}

func (o ProviderPlatformResponseDataLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ProviderBinaryUpload != nil {
		toSerialize["provider-binary-upload"] = o.ProviderBinaryUpload
	}
	if o.ProviderBinaryDownload != nil {
		toSerialize["provider-binary-download"] = o.ProviderBinaryDownload
	}
	return json.Marshal(toSerialize)
}

type NullableProviderPlatformResponseDataLinks struct {
	value *ProviderPlatformResponseDataLinks
	isSet bool
}

func (v NullableProviderPlatformResponseDataLinks) Get() *ProviderPlatformResponseDataLinks {
	return v.value
}

func (v *NullableProviderPlatformResponseDataLinks) Set(val *ProviderPlatformResponseDataLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderPlatformResponseDataLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderPlatformResponseDataLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderPlatformResponseDataLinks(val *ProviderPlatformResponseDataLinks) *NullableProviderPlatformResponseDataLinks {
	return &NullableProviderPlatformResponseDataLinks{value: val, isSet: true}
}

func (v NullableProviderPlatformResponseDataLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderPlatformResponseDataLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
