/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// GpgKey struct for GpgKey
type GpgKey struct {
	Data *GpgKeyData `json:"data,omitempty"`
}

// NewGpgKey instantiates a new GpgKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGpgKey() *GpgKey {
	this := GpgKey{}
	return &this
}

// NewGpgKeyWithDefaults instantiates a new GpgKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGpgKeyWithDefaults() *GpgKey {
	this := GpgKey{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GpgKey) GetData() GpgKeyData {
	if o == nil || o.Data == nil {
		var ret GpgKeyData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKey) GetDataOk() (*GpgKeyData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GpgKey) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GpgKeyData and assigns it to the Data field.
func (o *GpgKey) SetData(v GpgKeyData) {
	o.Data = &v
}

func (o GpgKey) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGpgKey struct {
	value *GpgKey
	isSet bool
}

func (v NullableGpgKey) Get() *GpgKey {
	return v.value
}

func (v *NullableGpgKey) Set(val *GpgKey) {
	v.value = val
	v.isSet = true
}

func (v NullableGpgKey) IsSet() bool {
	return v.isSet
}

func (v *NullableGpgKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGpgKey(val *GpgKey) *NullableGpgKey {
	return &NullableGpgKey{value: val, isSet: true}
}

func (v NullableGpgKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGpgKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
