/*
Terraform Private Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tfclient

import (
	"encoding/json"
)

// CreateRegistryProviderVersionResponseDataLinks struct for CreateRegistryProviderVersionResponseDataLinks
type CreateRegistryProviderVersionResponseDataLinks struct {
	ShasumsUpload    *string `json:"shasums-upload,omitempty"`
	ShasumsSigUpload *string `json:"shasums-sig-upload,omitempty"`
}

// NewCreateRegistryProviderVersionResponseDataLinks instantiates a new CreateRegistryProviderVersionResponseDataLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRegistryProviderVersionResponseDataLinks() *CreateRegistryProviderVersionResponseDataLinks {
	this := CreateRegistryProviderVersionResponseDataLinks{}
	return &this
}

// NewCreateRegistryProviderVersionResponseDataLinksWithDefaults instantiates a new CreateRegistryProviderVersionResponseDataLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRegistryProviderVersionResponseDataLinksWithDefaults() *CreateRegistryProviderVersionResponseDataLinks {
	this := CreateRegistryProviderVersionResponseDataLinks{}
	return &this
}

// GetShasumsUpload returns the ShasumsUpload field value if set, zero value otherwise.
func (o *CreateRegistryProviderVersionResponseDataLinks) GetShasumsUpload() string {
	if o == nil || o.ShasumsUpload == nil {
		var ret string
		return ret
	}
	return *o.ShasumsUpload
}

// GetShasumsUploadOk returns a tuple with the ShasumsUpload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderVersionResponseDataLinks) GetShasumsUploadOk() (*string, bool) {
	if o == nil || o.ShasumsUpload == nil {
		return nil, false
	}
	return o.ShasumsUpload, true
}

// HasShasumsUpload returns a boolean if a field has been set.
func (o *CreateRegistryProviderVersionResponseDataLinks) HasShasumsUpload() bool {
	if o != nil && o.ShasumsUpload != nil {
		return true
	}

	return false
}

// SetShasumsUpload gets a reference to the given string and assigns it to the ShasumsUpload field.
func (o *CreateRegistryProviderVersionResponseDataLinks) SetShasumsUpload(v string) {
	o.ShasumsUpload = &v
}

// GetShasumsSigUpload returns the ShasumsSigUpload field value if set, zero value otherwise.
func (o *CreateRegistryProviderVersionResponseDataLinks) GetShasumsSigUpload() string {
	if o == nil || o.ShasumsSigUpload == nil {
		var ret string
		return ret
	}
	return *o.ShasumsSigUpload
}

// GetShasumsSigUploadOk returns a tuple with the ShasumsSigUpload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRegistryProviderVersionResponseDataLinks) GetShasumsSigUploadOk() (*string, bool) {
	if o == nil || o.ShasumsSigUpload == nil {
		return nil, false
	}
	return o.ShasumsSigUpload, true
}

// HasShasumsSigUpload returns a boolean if a field has been set.
func (o *CreateRegistryProviderVersionResponseDataLinks) HasShasumsSigUpload() bool {
	if o != nil && o.ShasumsSigUpload != nil {
		return true
	}

	return false
}

// SetShasumsSigUpload gets a reference to the given string and assigns it to the ShasumsSigUpload field.
func (o *CreateRegistryProviderVersionResponseDataLinks) SetShasumsSigUpload(v string) {
	o.ShasumsSigUpload = &v
}

func (o CreateRegistryProviderVersionResponseDataLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ShasumsUpload != nil {
		toSerialize["shasums-upload"] = o.ShasumsUpload
	}
	if o.ShasumsSigUpload != nil {
		toSerialize["shasums-sig-upload"] = o.ShasumsSigUpload
	}
	return json.Marshal(toSerialize)
}

type NullableCreateRegistryProviderVersionResponseDataLinks struct {
	value *CreateRegistryProviderVersionResponseDataLinks
	isSet bool
}

func (v NullableCreateRegistryProviderVersionResponseDataLinks) Get() *CreateRegistryProviderVersionResponseDataLinks {
	return v.value
}

func (v *NullableCreateRegistryProviderVersionResponseDataLinks) Set(val *CreateRegistryProviderVersionResponseDataLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRegistryProviderVersionResponseDataLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRegistryProviderVersionResponseDataLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRegistryProviderVersionResponseDataLinks(val *CreateRegistryProviderVersionResponseDataLinks) *NullableCreateRegistryProviderVersionResponseDataLinks {
	return &NullableCreateRegistryProviderVersionResponseDataLinks{value: val, isSet: true}
}

func (v NullableCreateRegistryProviderVersionResponseDataLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRegistryProviderVersionResponseDataLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
